#ifndef __USER_EEPROM_H__
#define __USER_EEPROM_H__

#include "user_common.h"

#define DEFAULT_EEPROM_ID 0x5a

#define DEFAULT_VALVE_1_INTERVAL 1
#define DEFAULT_VALVE_1_START_TIME_1 24
#define DEFAULT_VALVE_1_START_TIME_2 6
#define DEFAULT_VALVE_1_START_TIME_3 12
#define DEFAULT_VALVE_1_START_TIME_4 18
#define DEFAULT_VALVE_1_START_TIME_5 0
#define DEFAULT_VALVE_1_START_TIME_6 0
#define DEFAULT_VALVE_1_START_TIME_7 0
#define DEFAULT_VALVE_1_START_TIME_8 0
#define DEFAULT_VALVE_1_START_TIME_9 0
#define DEFAULT_VALVE_1_START_TIME_10 0
#define DEFAULT_VALVE_1_ON_TIME 300

#define DEFAULT_PUMP_1_ON_DELAY 10

#define DEFAULT_UV_LAMP_OFF_DELAY 10

#define DEFAULT_AERATION_3_OFF_DELAY 10

#define DEFAULT_PUMP_3_INTERVAL 1
#define DEFAULT_PUMP_3_START_TIME_1 24
#define DEFAULT_PUMP_3_START_TIME_2 0
#define DEFAULT_PUMP_3_START_TIME_3 0
#define DEFAULT_PUMP_3_START_TIME_4 0
#define DEFAULT_PUMP_3_START_TIME_5 0
#define DEFAULT_PUMP_3_ON_TIME 4

#define DEFAULT_WATER_PUMP_4_TIMEOUT 30

#define DEFAULT_SLUDGE_DISCHARGE_INTERVAL 3
#define DEFAULT_SLUDGE_DISCHARGE_START_TIME_1 8
#define DEFAULT_SLUDGE_DISCHARGE_START_TIME_2 13
#define DEFAULT_SLUDGE_DISCHARGE_START_TIME_3 17
#define DEFAULT_SLUDGE_DISCHARGE_START_TIME_4 0
#define DEFAULT_SLUDGE_DISCHARGE_START_TIME_5 0
#define DEFAULT_SLUDGE_DISCHARGE_START_TIME_6 0
#define DEFAULT_SLUDGE_DISCHARGE_START_TIME_7 0
#define DEFAULT_SLUDGE_DISCHARGE_START_TIME_8 0
#define DEFAULT_SLUDGE_DISCHARGE_START_TIME_9 0
#define DEFAULT_SLUDGE_DISCHARGE_START_TIME_10 0

#define DEFAULT_WATER_PUMP_1_ON_TIME 12

#define DEFAULT_WATER_PUMP_2_ON_TIME 168

#define DEFAULT_VALVE_3_ON_TIME 28
#define DEFAULT_VALVE_3_OFF_DELAY 0
#define DEFAULT_VALVE_4_ON_TIME 10
#define DEFAULT_VALVE_4_OFF_DELAY 0
#define DEFAULT_VALVE_5_ON_TIME 15
#define DEFAULT_VALVE_5_OFF_DELAY 1
#define DEFAULT_VALVE_6_ON_TIME 6
#define DEFAULT_VALVE_6_OFF_DELAY 0

#define DEFAULT_MOTOR_8_OFF_DELAY 600

#define DEFAULT_WATER_PUMP_5_INTERVAL 1
#define DEFAULT_WATER_PUMP_5_START_TIME_1 6
#define DEFAULT_WATER_PUMP_5_START_TIME_2 0
#define DEFAULT_WATER_PUMP_5_START_TIME_3 0
#define DEFAULT_WATER_PUMP_5_START_TIME_4 0
#define DEFAULT_WATER_PUMP_5_START_TIME_5 0
#define DEFAULT_WATER_PUMP_5_START_TIME_6 0
#define DEFAULT_WATER_PUMP_5_START_TIME_7 0
#define DEFAULT_WATER_PUMP_5_START_TIME_8 0
#define DEFAULT_WATER_PUMP_5_START_TIME_9 0
#define DEFAULT_WATER_PUMP_5_START_TIME_10 0
#define DEFAULT_WATER_PUMP_5_START_TIME_11 0
#define DEFAULT_WATER_PUMP_5_START_TIME_12 0
#define DEFAULT_WATER_PUMP_5_START_TIME_13 0
#define DEFAULT_WATER_PUMP_5_START_TIME_14 0
#define DEFAULT_WATER_PUMP_5_START_TIME_15 0
#define DEFAULT_WATER_PUMP_5_START_TIME_16 0
#define DEFAULT_WATER_PUMP_5_START_TIME_17 0
#define DEFAULT_WATER_PUMP_5_START_TIME_18 0
#define DEFAULT_WATER_PUMP_5_START_TIME_19 0
#define DEFAULT_WATER_PUMP_5_START_TIME_20 0
#define DEFAULT_WATER_PUMP_5_START_TIME_21 0
#define DEFAULT_WATER_PUMP_5_START_TIME_22 0
#define DEFAULT_WATER_PUMP_5_START_TIME_23 0
#define DEFAULT_WATER_PUMP_5_START_TIME_24 0
#define DEFAULT_WATER_PUMP_5_ON_TIME 30

#define DEFAULT_VALVE_2_ON_DELAY_1 16200
#define DEFAULT_VALVE_2_ON_DELAY_2 16200
#define DEFAULT_VALVE_2_ON_DELAY_3 16200
#define DEFAULT_VALVE_2_ON_DELAY_4 0
#define DEFAULT_VALVE_2_ON_DELAY_5 0
#define DEFAULT_VALVE_2_ON_DELAY_6 0
#define DEFAULT_VALVE_2_ON_DELAY_7 0
#define DEFAULT_VALVE_2_ON_DELAY_8 0
#define DEFAULT_VALVE_2_ON_DELAY_9 0
#define DEFAULT_VALVE_2_ON_DELAY_10 0
#define DEFAULT_VALVE_2_ON_TIME 1200

#define DEFAULT_MOTOR_1_OP_TIME 36000
#define DEFAULT_MOTOR_1_CW_TIME 10
#define DEFAULT_MOTOR_1_CCW_TIME 10
#define DEFAULT_MOTOR_1_STOP_TIME 180

#define DEFAULT_FAN_1_OP_TIME 216000
#define DEFAULT_FAN_2_OP_TIME 216000
#define DEFAULT_PTC_FAN_OP_TIME 216000

#define DEFAULT_MOTOR_2_DRY_OP_TIME 180000
#define DEFAULT_MOTOR_2_DRY_CW_TIME 15
#define DEFAULT_MOTOR_2_DRY_CCW_TIME 15
#define DEFAULT_MOTOR_2_DRY_STOP_TIME 2
#define DEFAULT_MOTOR_2_CRUSH_OP_TIME 1200
#define DEFAULT_MOTOR_2_CRUSH_CW_TIME 7
#define DEFAULT_MOTOR_2_CRUSH_CCW_TIME 9
#define DEFAULT_MOTOR_2_CRUSH_STOP_TIME 2
#define DEFAULT_MOTOR_2_OUT_OP_TIME 3600
#define DEFAULT_MOTOR_2_OUT_CW_TIME 10
#define DEFAULT_MOTOR_2_OUT_CCW_TIME 12
#define DEFAULT_MOTOR_2_OUT_STOP_TIME 2

#define DEFAULT_ACTUATOR_1_OP_TIME 1

#define DEFAULT_MOTOR_3_OP_TIME 3600

#define DEFAULT_HEATER_1_OP_TIME 21600
#define DEFAULT_HEATER_1_TEMP_UP_LIMIT_TIME 1800

#define DEFAULT_PUMP_2_OP_TIME 7200

#define DEFAULT_MOTOR_4_OP_TIME 21600
#define DEFAULT_MOTOR_4_CW_TIME 20
#define DEFAULT_MOTOR_4_CCW_TIME 6

#define DEFAULT_MOTOR_5_OP_TIME 21600
#define DEFAULT_MOTOR_5_ON_TIME 5
#define DEFAULT_MOTOR_5_OFF_TIME 175

#define DEFAULT_MOTOR_6_OP_TIME 21600
#define DEFAULT_MOTOR_6_CW_TIME 8
#define DEFAULT_MOTOR_6_CCW_TIME 14

#define DEFAULT_MOTOR_7_OP_TIME 1800
#define DEFAULT_MOTOR_7_SET_RPM 5000

#define DEFAULT_RADIATOR_ON_TEMP 4
#define DEFAULT_RADIATOR_OFF_TEMP 6

#define DEFAULT_HYSTERESIS_TIME 1

#define DEFAULT_RTC_DATE 0x26010104
#define DEFAULT_RTC_TIME 0x00090000

typedef enum
{
    eeprom_ID = 0,
	eeprom_VALVE_1_INTERVAL = eeprom_ID + 4,
	eeprom_VALVE_1_START_TIME_1 = eeprom_VALVE_1_INTERVAL + 4,
	eeprom_VALVE_1_START_TIME_2 = eeprom_VALVE_1_START_TIME_1 + 4,
	eeprom_VALVE_1_START_TIME_3 = eeprom_VALVE_1_START_TIME_2 + 4,
	eeprom_VALVE_1_START_TIME_4 = eeprom_VALVE_1_START_TIME_3 + 4,
	eeprom_VALVE_1_START_TIME_5 = eeprom_VALVE_1_START_TIME_4 + 4,
	eeprom_VALVE_1_START_TIME_6 = eeprom_VALVE_1_START_TIME_5 + 4,
	eeprom_VALVE_1_START_TIME_7 = eeprom_VALVE_1_START_TIME_6 + 4,
	eeprom_VALVE_1_START_TIME_8 = eeprom_VALVE_1_START_TIME_7 + 4,
	eeprom_VALVE_1_START_TIME_9 = eeprom_VALVE_1_START_TIME_8 + 4,
	eeprom_VALVE_1_START_TIME_10 = eeprom_VALVE_1_START_TIME_9 + 4,
	eeprom_VALVE_1_ON_TIME = eeprom_VALVE_1_START_TIME_10 + 4,
	
	eeprom_PUMP_1_ON_DELAY = eeprom_VALVE_1_ON_TIME + 4,
	
	eeprom_UV_LAMP_OFF_DELAY = eeprom_PUMP_1_ON_DELAY + 4,
	
	eeprom_AERATION_3_OFF_DELAY = eeprom_UV_LAMP_OFF_DELAY + 4,
	
	eeprom_PUMP_3_INTERVAL = eeprom_AERATION_3_OFF_DELAY + 4,
	eeprom_PUMP_3_START_TIME_1 = eeprom_PUMP_3_INTERVAL + 4,
	eeprom_PUMP_3_START_TIME_2 = eeprom_PUMP_3_START_TIME_1 + 4,
	eeprom_PUMP_3_START_TIME_3 = eeprom_PUMP_3_START_TIME_2 + 4,
	eeprom_PUMP_3_START_TIME_4 = eeprom_PUMP_3_START_TIME_3 + 4,
	eeprom_PUMP_3_START_TIME_5 = eeprom_PUMP_3_START_TIME_4 + 4,
	eeprom_PUMP_3_ON_TIME = eeprom_PUMP_3_START_TIME_5 + 4,
	
	eeprom_WATER_PUMP_4_TIMEOUT = eeprom_PUMP_3_ON_TIME + 4,
	
	eeprom_SLUDGE_DISCHARGE_INTERVAL = eeprom_WATER_PUMP_4_TIMEOUT + 4,
	eeprom_SLUDGE_DISCHARGE_START_TIME_1 = eeprom_SLUDGE_DISCHARGE_INTERVAL + 4,
	eeprom_SLUDGE_DISCHARGE_START_TIME_2 = eeprom_SLUDGE_DISCHARGE_START_TIME_1 + 4,
	eeprom_SLUDGE_DISCHARGE_START_TIME_3 = eeprom_SLUDGE_DISCHARGE_START_TIME_2 + 4,
	eeprom_SLUDGE_DISCHARGE_START_TIME_4 = eeprom_SLUDGE_DISCHARGE_START_TIME_3 + 4,
	eeprom_SLUDGE_DISCHARGE_START_TIME_5 = eeprom_SLUDGE_DISCHARGE_START_TIME_4 + 4,
	eeprom_SLUDGE_DISCHARGE_START_TIME_6 = eeprom_SLUDGE_DISCHARGE_START_TIME_5 + 4,
	eeprom_SLUDGE_DISCHARGE_START_TIME_7 = eeprom_SLUDGE_DISCHARGE_START_TIME_6 + 4,
	eeprom_SLUDGE_DISCHARGE_START_TIME_8 = eeprom_SLUDGE_DISCHARGE_START_TIME_7 + 4,
	eeprom_SLUDGE_DISCHARGE_START_TIME_9 = eeprom_SLUDGE_DISCHARGE_START_TIME_8 + 4,
	eeprom_SLUDGE_DISCHARGE_START_TIME_10 = eeprom_SLUDGE_DISCHARGE_START_TIME_9 + 4,

	eeprom_WATER_PUMP_1_ON_TIME = eeprom_SLUDGE_DISCHARGE_START_TIME_10 + 4,
	
	eeprom_WATER_PUMP_2_ON_TIME = eeprom_WATER_PUMP_1_ON_TIME + 4,

	eeprom_VALVE_3_ON_TIME = eeprom_WATER_PUMP_2_ON_TIME + 4,
	eeprom_VALVE_3_OFF_DELAY = eeprom_VALVE_3_ON_TIME + 4,
	eeprom_VALVE_4_ON_TIME = eeprom_VALVE_3_OFF_DELAY + 4,
	eeprom_VALVE_4_OFF_DELAY = eeprom_VALVE_4_ON_TIME + 4,
	eeprom_VALVE_5_ON_TIME = eeprom_VALVE_4_OFF_DELAY + 4,
	eeprom_VALVE_5_OFF_DELAY = eeprom_VALVE_5_ON_TIME + 4,
	eeprom_VALVE_6_ON_TIME = eeprom_VALVE_5_OFF_DELAY + 4,
	eeprom_VALVE_6_OFF_DELAY = eeprom_VALVE_6_ON_TIME + 4,
	
	eeprom_MOTOR_8_OFF_DELAY = eeprom_VALVE_6_OFF_DELAY + 4,
	
	eeprom_WATER_PUMP_5_INTERVAL = eeprom_MOTOR_8_OFF_DELAY + 4,
	eeprom_WATER_PUMP_5_START_TIME_1 = eeprom_WATER_PUMP_5_INTERVAL + 4,
	eeprom_WATER_PUMP_5_START_TIME_2 = eeprom_WATER_PUMP_5_START_TIME_1 + 4,
	eeprom_WATER_PUMP_5_START_TIME_3 = eeprom_WATER_PUMP_5_START_TIME_2 + 4,
	eeprom_WATER_PUMP_5_START_TIME_4 = eeprom_WATER_PUMP_5_START_TIME_3 + 4,
	eeprom_WATER_PUMP_5_START_TIME_5 = eeprom_WATER_PUMP_5_START_TIME_4 + 4,
	eeprom_WATER_PUMP_5_START_TIME_6 = eeprom_WATER_PUMP_5_START_TIME_5 + 4,
	eeprom_WATER_PUMP_5_START_TIME_7 = eeprom_WATER_PUMP_5_START_TIME_6 + 4,
	eeprom_WATER_PUMP_5_START_TIME_8 = eeprom_WATER_PUMP_5_START_TIME_7 + 4,
	eeprom_WATER_PUMP_5_START_TIME_9 = eeprom_WATER_PUMP_5_START_TIME_8 + 4,
	eeprom_WATER_PUMP_5_START_TIME_10 = eeprom_WATER_PUMP_5_START_TIME_9 + 4,
	eeprom_WATER_PUMP_5_START_TIME_11 = eeprom_WATER_PUMP_5_START_TIME_10 + 4,
	eeprom_WATER_PUMP_5_START_TIME_12 = eeprom_WATER_PUMP_5_START_TIME_11 + 4,
	eeprom_WATER_PUMP_5_START_TIME_13 = eeprom_WATER_PUMP_5_START_TIME_12 + 4,
	eeprom_WATER_PUMP_5_START_TIME_14 = eeprom_WATER_PUMP_5_START_TIME_13 + 4,
	eeprom_WATER_PUMP_5_START_TIME_15 = eeprom_WATER_PUMP_5_START_TIME_14 + 4,
	eeprom_WATER_PUMP_5_START_TIME_16 = eeprom_WATER_PUMP_5_START_TIME_15 + 4,
	eeprom_WATER_PUMP_5_START_TIME_17 = eeprom_WATER_PUMP_5_START_TIME_16 + 4,
	eeprom_WATER_PUMP_5_START_TIME_18 = eeprom_WATER_PUMP_5_START_TIME_17 + 4,
	eeprom_WATER_PUMP_5_START_TIME_19 = eeprom_WATER_PUMP_5_START_TIME_18 + 4,
	eeprom_WATER_PUMP_5_START_TIME_20 = eeprom_WATER_PUMP_5_START_TIME_19 + 4,
	eeprom_WATER_PUMP_5_START_TIME_21 = eeprom_WATER_PUMP_5_START_TIME_20 + 4,
	eeprom_WATER_PUMP_5_START_TIME_22 = eeprom_WATER_PUMP_5_START_TIME_21 + 4,
	eeprom_WATER_PUMP_5_START_TIME_23 = eeprom_WATER_PUMP_5_START_TIME_22 + 4,
	eeprom_WATER_PUMP_5_START_TIME_24 = eeprom_WATER_PUMP_5_START_TIME_23 + 4,
	eeprom_WATER_PUMP_5_ON_TIME = eeprom_WATER_PUMP_5_START_TIME_24 + 4,

	eeprom_VALVE_2_ON_DELAY_1 = eeprom_WATER_PUMP_5_ON_TIME + 4,
	eeprom_VALVE_2_ON_DELAY_2 = eeprom_VALVE_2_ON_DELAY_1 + 4,
	eeprom_VALVE_2_ON_DELAY_3 = eeprom_VALVE_2_ON_DELAY_2 + 4,
	eeprom_VALVE_2_ON_DELAY_4 = eeprom_VALVE_2_ON_DELAY_3 + 4,
	eeprom_VALVE_2_ON_DELAY_5 = eeprom_VALVE_2_ON_DELAY_4 + 4,
	eeprom_VALVE_2_ON_DELAY_6 = eeprom_VALVE_2_ON_DELAY_5 + 4,
	eeprom_VALVE_2_ON_DELAY_7 = eeprom_VALVE_2_ON_DELAY_6 + 4,
	eeprom_VALVE_2_ON_DELAY_8 = eeprom_VALVE_2_ON_DELAY_7 + 4,
	eeprom_VALVE_2_ON_DELAY_9 = eeprom_VALVE_2_ON_DELAY_8 + 4,
	eeprom_VALVE_2_ON_DELAY_10 = eeprom_VALVE_2_ON_DELAY_9 + 4,
	eeprom_VALVE_2_ON_TIME = eeprom_VALVE_2_ON_DELAY_10 + 4,
	
	eeprom_MOTOR_1_OP_TIME = eeprom_VALVE_2_ON_TIME + 4,
	eeprom_MOTOR_1_CW_TIME = eeprom_MOTOR_1_OP_TIME + 4,
	eeprom_MOTOR_1_CCW_TIME = eeprom_MOTOR_1_CW_TIME + 4,
	eeprom_MOTOR_1_STOP_TIME = eeprom_MOTOR_1_CCW_TIME + 4,
	
	eeprom_FAN_1_OP_TIME = eeprom_MOTOR_1_STOP_TIME + 4,
	eeprom_FAN_2_OP_TIME = eeprom_FAN_1_OP_TIME + 4,
	eeprom_PTC_FAN_OP_TIME = eeprom_FAN_2_OP_TIME + 4,
	
	eeprom_MOTOR_2_DRY_OP_TIME = eeprom_PTC_FAN_OP_TIME + 4,
	eeprom_MOTOR_2_DRY_CW_TIME = eeprom_MOTOR_2_DRY_OP_TIME + 4,
	eeprom_MOTOR_2_DRY_CCW_TIME = eeprom_MOTOR_2_DRY_CW_TIME + 4,
	eeprom_MOTOR_2_DRY_STOP_TIME = eeprom_MOTOR_2_DRY_CCW_TIME + 4,
	eeprom_MOTOR_2_CRUSH_OP_TIME = eeprom_MOTOR_2_DRY_STOP_TIME + 4,
	eeprom_MOTOR_2_CRUSH_CW_TIME = eeprom_MOTOR_2_CRUSH_OP_TIME + 4,
	eeprom_MOTOR_2_CRUSH_CCW_TIME = eeprom_MOTOR_2_CRUSH_CW_TIME + 4,
	eeprom_MOTOR_2_CRUSH_STOP_TIME = eeprom_MOTOR_2_CRUSH_CCW_TIME + 4,
	eeprom_MOTOR_2_OUT_OP_TIME = eeprom_MOTOR_2_CRUSH_STOP_TIME + 4,
	eeprom_MOTOR_2_OUT_CW_TIME = eeprom_MOTOR_2_OUT_OP_TIME + 4,
	eeprom_MOTOR_2_OUT_CCW_TIME = eeprom_MOTOR_2_OUT_CW_TIME + 4,
	eeprom_MOTOR_2_OUT_STOP_TIME = eeprom_MOTOR_2_OUT_CCW_TIME + 4,
	
	eeprom_ACTUATOR_1_OP_TIME = eeprom_MOTOR_2_OUT_STOP_TIME + 4,
	
	eeprom_MOTOR_3_OP_TIME = eeprom_ACTUATOR_1_OP_TIME + 4,
	
	eeprom_HEATER_1_OP_TIME = eeprom_MOTOR_3_OP_TIME + 4,
	eeprom_HEATER_1_TEMP_UP_LIMIT_TIME = eeprom_HEATER_1_OP_TIME + 4,
	
	eeprom_PUMP_2_OP_TIME = eeprom_HEATER_1_TEMP_UP_LIMIT_TIME + 4,
	
	eeprom_MOTOR_4_OP_TIME = eeprom_PUMP_2_OP_TIME + 4,
	eeprom_MOTOR_4_CW_TIME = eeprom_MOTOR_4_OP_TIME + 4,
	eeprom_MOTOR_4_CCW_TIME = eeprom_MOTOR_4_CW_TIME + 4,
	
	eeprom_MOTOR_5_OP_TIME = eeprom_MOTOR_4_CCW_TIME + 4,
	eeprom_MOTOR_5_ON_TIME = eeprom_MOTOR_5_OP_TIME + 4,
	eeprom_MOTOR_5_OFF_TIME = eeprom_MOTOR_5_ON_TIME + 4,
	
	eeprom_MOTOR_6_OP_TIME = eeprom_MOTOR_5_OFF_TIME + 4,
	eeprom_MOTOR_6_CW_TIME = eeprom_MOTOR_6_OP_TIME + 4,
	eeprom_MOTOR_6_CCW_TIME = eeprom_MOTOR_6_CW_TIME + 4,
	
	eeprom_MOTOR_7_OP_TIME = eeprom_MOTOR_6_CCW_TIME + 4,
	eeprom_MOTOR_7_SET_RPM = eeprom_MOTOR_7_OP_TIME + 4,
	
	eeprom_RADIATOR_ON_TEMP = eeprom_MOTOR_7_SET_RPM + 4,
	eeprom_RADIATOR_OFF_TEMP = eeprom_RADIATOR_ON_TEMP + 4,
	
	eeprom_HYSTERESIS_TIME = eeprom_RADIATOR_OFF_TEMP + 4,
	
	eeprom_RTC_DATE = eeprom_HYSTERESIS_TIME + 4,
	eeprom_RTC_TIME = eeprom_RTC_DATE + 4,

    eeprom_Crc = eeprom_RTC_TIME + 4,
	
    eeprom_Size = eeprom_Crc + 4,
} e_eeprom_address;

typedef struct
{
	uint8_t Flag;
    uint8_t Verify;
	uint8_t Data[eeprom_Size];
} eeprom_t;

void eeprom_Read(void);
void eeprom_Write(void);

#endif