#ifndef __USER_MODBUS_H__
#define __USER_MODBUS_H__

#include "user_common.h"

#define RTU_HMI_ADDRESS 1
#define RTU_PC_ADDRESS 2

#define COILS_ADDR_MAX 1
#define REGS_ADDR_MAX (uint32_t)(255 * 2)
#define REGS_SYSTEM_PARAMETER_ADDR_MAX (uint32_t)(255 * 2)
#define REGS_SYSTEM_PARAMETER_ADDR 100
#define SLAVE_REGS_ADDR_MAX (uint32_t)(10 * 2)

#define RTU_PC_MAX_SLAVES 3
#define RTU_PC_START_SLAVE_ID 1
#define RTU_PC_READ_INTERVAL_MS 1000

#define ENVIRONMENT_SENSOR_MAX 2
#define POWER_METER_MAX 1
#define TEMPERATURE_CONTROLLER_MAX 1

typedef struct
{
	uint16_t current_id;
    uint16_t holding_data[SLAVE_REGS_ADDR_MAX + 1];
} slave_data_t;

typedef enum
{
	ID_SW_VER = 0,
	ID_PRODUCT_ID,
	ID_DEV_ADDR,
	ID_DEV_OPERATION,
	ID_DEV_STATE,
	ID_POWER_METER_V,
	ID_POWER_METER_A,
	ID_POWER_METER_W,
	ID_POWER_METER_WH,
	ID_ENVIRONMENT_IN = ID_POWER_METER_WH + 2,
	ID_ENVIRONMENT_OUT,
	ID_FLOW_METER,
	ID_FILTER_GAUGE,
	ID_RADIATOR,
	ID_FAN_3,
	ID_SIGNAL_INDICATOR,
	
	ID_VALVE_1,
	ID_PUMP_1,
	ID_UV_LAMP,
	ID_AERATION_3,
	ID_PUMP_3,
	ID_VALVE_7,
	ID_VALVE_8,
	ID_WATER_PUMP_4,
	ID_AERATION_1,
	ID_AERATION_2,
	
	ID_WATER_PUMP_1,
	ID_WATER_PUMP_2,
	ID_WATER_PUMP_3,
	ID_VALVE_3,
	ID_VALVE_4,
	ID_VALVE_5,
	ID_VALVE_6,
	ID_MOTOR_8,
	ID_MOTOR_9,
	ID_WATER_PUMP_5,
	
	ID_VALVE_2,
	ID_MOTOR_1,
	ID_FAN_1,
	ID_FAN_2,
	ID_PTC_FAN,
	ID_MOTOR_2,
	ID_ACTUATOR_1,
	
	ID_MOTOR_3,
	ID_HEATER_1,
	ID_PUMP_2,
	ID_MOTOR_4,
	ID_MOTOR_5,
	ID_MOTOR_6,
	ID_MOTOR_7,
	ID_MOTOR_7_FG,
	
	ID_LEVEL_SENSOR,
	ID_SWITCH,
	ID_SENSOR,

	ID_VALVE_1_INTERVAL = 100,
	ID_VALVE_1_START_TIME_1 = ID_VALVE_1_INTERVAL + 2,
	ID_VALVE_1_START_TIME_2 = ID_VALVE_1_START_TIME_1 + 2,
	ID_VALVE_1_START_TIME_3 = ID_VALVE_1_START_TIME_2 + 2,
	ID_VALVE_1_START_TIME_4 = ID_VALVE_1_START_TIME_3 + 2,
	ID_VALVE_1_START_TIME_5 = ID_VALVE_1_START_TIME_4 + 2,
	ID_VALVE_1_START_TIME_6 = ID_VALVE_1_START_TIME_5 + 2,
	ID_VALVE_1_START_TIME_7 = ID_VALVE_1_START_TIME_6 + 2,
	ID_VALVE_1_START_TIME_8 = ID_VALVE_1_START_TIME_7 + 2,
	ID_VALVE_1_START_TIME_9 = ID_VALVE_1_START_TIME_8 + 2,
	ID_VALVE_1_START_TIME_10 = ID_VALVE_1_START_TIME_9 + 2,
	ID_VALVE_1_ON_TIME = ID_VALVE_1_START_TIME_10 + 2,
	
	ID_PUMP_1_ON_DELAY = ID_VALVE_1_ON_TIME + 2,
	
	ID_UV_LAMP_OFF_DELAY = ID_PUMP_1_ON_DELAY + 2,
	
	ID_AERATION_3_OFF_DELAY = ID_UV_LAMP_OFF_DELAY + 2,
	
	ID_PUMP_3_INTERVAL = ID_AERATION_3_OFF_DELAY + 2,
	ID_PUMP_3_START_TIME_1 = ID_PUMP_3_INTERVAL + 2,
	ID_PUMP_3_START_TIME_2 = ID_PUMP_3_START_TIME_1 + 2,
	ID_PUMP_3_START_TIME_3 = ID_PUMP_3_START_TIME_2 + 2,
	ID_PUMP_3_START_TIME_4 = ID_PUMP_3_START_TIME_3 + 2,
	ID_PUMP_3_START_TIME_5 = ID_PUMP_3_START_TIME_4 + 2,
	ID_PUMP_3_ON_TIME = ID_PUMP_3_START_TIME_5 + 2,
	
	ID_WATER_PUMP_4_TIMEOUT = ID_PUMP_3_ON_TIME + 2,
	
	ID_SLUDGE_DISCHARGE_INTERVAL = ID_WATER_PUMP_4_TIMEOUT + 2,
	ID_SLUDGE_DISCHARGE_START_TIME_1 = ID_SLUDGE_DISCHARGE_INTERVAL + 2,
	ID_SLUDGE_DISCHARGE_START_TIME_2 = ID_SLUDGE_DISCHARGE_START_TIME_1 + 2,
	ID_SLUDGE_DISCHARGE_START_TIME_3 = ID_SLUDGE_DISCHARGE_START_TIME_2 + 2,
	ID_SLUDGE_DISCHARGE_START_TIME_4 = ID_SLUDGE_DISCHARGE_START_TIME_3 + 2,
	ID_SLUDGE_DISCHARGE_START_TIME_5 = ID_SLUDGE_DISCHARGE_START_TIME_4 + 2,
	ID_SLUDGE_DISCHARGE_START_TIME_6 = ID_SLUDGE_DISCHARGE_START_TIME_5 + 2,
	ID_SLUDGE_DISCHARGE_START_TIME_7 = ID_SLUDGE_DISCHARGE_START_TIME_6 + 2,
	ID_SLUDGE_DISCHARGE_START_TIME_8 = ID_SLUDGE_DISCHARGE_START_TIME_7 + 2,
	ID_SLUDGE_DISCHARGE_START_TIME_9 = ID_SLUDGE_DISCHARGE_START_TIME_8 + 2,
	ID_SLUDGE_DISCHARGE_START_TIME_10 = ID_SLUDGE_DISCHARGE_START_TIME_9 + 2,

	ID_WATER_PUMP_1_ON_TIME = ID_SLUDGE_DISCHARGE_START_TIME_10 + 2,

	ID_WATER_PUMP_2_ON_TIME = ID_WATER_PUMP_1_ON_TIME + 2,

	ID_VALVE_3_ON_TIME = ID_WATER_PUMP_2_ON_TIME + 2,
	ID_VALVE_3_OFF_DELAY = ID_VALVE_3_ON_TIME + 2,
	ID_VALVE_4_ON_TIME = ID_VALVE_3_OFF_DELAY + 2,
	ID_VALVE_4_OFF_DELAY = ID_VALVE_4_ON_TIME + 2,
	ID_VALVE_5_ON_TIME = ID_VALVE_4_OFF_DELAY + 2,
	ID_VALVE_5_OFF_DELAY = ID_VALVE_5_ON_TIME + 2,
	ID_VALVE_6_ON_TIME = ID_VALVE_5_OFF_DELAY + 2,
	ID_VALVE_6_OFF_DELAY = ID_VALVE_6_ON_TIME + 2,
	
	ID_MOTOR_8_OFF_DELAY = ID_VALVE_6_OFF_DELAY + 2,
	
	ID_WATER_PUMP_5_INTERVAL = ID_MOTOR_8_OFF_DELAY + 2,
	ID_WATER_PUMP_5_START_TIME_1 = ID_WATER_PUMP_5_INTERVAL + 2,
	ID_WATER_PUMP_5_START_TIME_2 = ID_WATER_PUMP_5_START_TIME_1 + 2,
	ID_WATER_PUMP_5_START_TIME_3 = ID_WATER_PUMP_5_START_TIME_2 + 2,
	ID_WATER_PUMP_5_START_TIME_4 = ID_WATER_PUMP_5_START_TIME_3 + 2,
	ID_WATER_PUMP_5_START_TIME_5 = ID_WATER_PUMP_5_START_TIME_4 + 2,
	ID_WATER_PUMP_5_START_TIME_6 = ID_WATER_PUMP_5_START_TIME_5 + 2,
	ID_WATER_PUMP_5_START_TIME_7 = ID_WATER_PUMP_5_START_TIME_6 + 2,
	ID_WATER_PUMP_5_START_TIME_8 = ID_WATER_PUMP_5_START_TIME_7 + 2,
	ID_WATER_PUMP_5_START_TIME_9 = ID_WATER_PUMP_5_START_TIME_8 + 2,
	ID_WATER_PUMP_5_START_TIME_10 = ID_WATER_PUMP_5_START_TIME_9 + 2,
	ID_WATER_PUMP_5_START_TIME_11 = ID_WATER_PUMP_5_START_TIME_10 + 2,
	ID_WATER_PUMP_5_START_TIME_12 = ID_WATER_PUMP_5_START_TIME_11 + 2,
	ID_WATER_PUMP_5_START_TIME_13 = ID_WATER_PUMP_5_START_TIME_12 + 2,
	ID_WATER_PUMP_5_START_TIME_14 = ID_WATER_PUMP_5_START_TIME_13 + 2,
	ID_WATER_PUMP_5_START_TIME_15 = ID_WATER_PUMP_5_START_TIME_14 + 2,
	ID_WATER_PUMP_5_START_TIME_16 = ID_WATER_PUMP_5_START_TIME_15 + 2,
	ID_WATER_PUMP_5_START_TIME_17 = ID_WATER_PUMP_5_START_TIME_16 + 2,
	ID_WATER_PUMP_5_START_TIME_18 = ID_WATER_PUMP_5_START_TIME_17 + 2,
	ID_WATER_PUMP_5_START_TIME_19 = ID_WATER_PUMP_5_START_TIME_18 + 2,
	ID_WATER_PUMP_5_START_TIME_20 = ID_WATER_PUMP_5_START_TIME_19 + 2,
	ID_WATER_PUMP_5_START_TIME_21 = ID_WATER_PUMP_5_START_TIME_20 + 2,
	ID_WATER_PUMP_5_START_TIME_22 = ID_WATER_PUMP_5_START_TIME_21 + 2,
	ID_WATER_PUMP_5_START_TIME_23 = ID_WATER_PUMP_5_START_TIME_22 + 2,
	ID_WATER_PUMP_5_START_TIME_24 = ID_WATER_PUMP_5_START_TIME_23 + 2,
	ID_WATER_PUMP_5_ON_TIME = ID_WATER_PUMP_5_START_TIME_24 + 2,

	ID_VALVE_2_ON_DELAY_1 = ID_WATER_PUMP_5_ON_TIME + 2,
	ID_VALVE_2_ON_DELAY_2 = ID_VALVE_2_ON_DELAY_1 + 2,
	ID_VALVE_2_ON_DELAY_3 = ID_VALVE_2_ON_DELAY_2 + 2,
	ID_VALVE_2_ON_DELAY_4 = ID_VALVE_2_ON_DELAY_3 + 2,
	ID_VALVE_2_ON_DELAY_5 = ID_VALVE_2_ON_DELAY_4 + 2,
	ID_VALVE_2_ON_DELAY_6 = ID_VALVE_2_ON_DELAY_5 + 2,
	ID_VALVE_2_ON_DELAY_7 = ID_VALVE_2_ON_DELAY_6 + 2,
	ID_VALVE_2_ON_DELAY_8 = ID_VALVE_2_ON_DELAY_7 + 2,
	ID_VALVE_2_ON_DELAY_9 = ID_VALVE_2_ON_DELAY_8 + 2,
	ID_VALVE_2_ON_DELAY_10 = ID_VALVE_2_ON_DELAY_9 + 2,
	ID_VALVE_2_ON_TIME = ID_VALVE_2_ON_DELAY_10 + 2,

	ID_MOTOR_1_OP_TIME = ID_VALVE_2_ON_TIME + 2,
	ID_MOTOR_1_CW_TIME = ID_MOTOR_1_OP_TIME + 2,
	ID_MOTOR_1_CCW_TIME = ID_MOTOR_1_CW_TIME + 2,
	ID_MOTOR_1_STOP_TIME = ID_MOTOR_1_CCW_TIME + 2,
	
	ID_FAN_1_OP_TIME = ID_MOTOR_1_STOP_TIME + 2,
	ID_FAN_2_OP_TIME = ID_FAN_1_OP_TIME + 2,
	ID_PTC_FAN_OP_TIME = ID_FAN_2_OP_TIME + 2,
	
	ID_MOTOR_2_DRY_OP_TIME = ID_PTC_FAN_OP_TIME + 2,
	ID_MOTOR_2_DRY_CW_TIME = ID_MOTOR_2_DRY_OP_TIME + 2,
	ID_MOTOR_2_DRY_CCW_TIME = ID_MOTOR_2_DRY_CW_TIME + 2,
	ID_MOTOR_2_DRY_STOP_TIME = ID_MOTOR_2_DRY_CCW_TIME + 2,
	ID_MOTOR_2_CRUSH_OP_TIME = ID_MOTOR_2_DRY_STOP_TIME + 2,
	ID_MOTOR_2_CRUSH_CW_TIME = ID_MOTOR_2_CRUSH_OP_TIME + 2,
	ID_MOTOR_2_CRUSH_CCW_TIME = ID_MOTOR_2_CRUSH_CW_TIME + 2,
	ID_MOTOR_2_CRUSH_STOP_TIME = ID_MOTOR_2_CRUSH_CCW_TIME + 2,
	ID_MOTOR_2_OUT_OP_TIME = ID_MOTOR_2_CRUSH_STOP_TIME + 2,
	ID_MOTOR_2_OUT_CW_TIME = ID_MOTOR_2_OUT_OP_TIME + 2,
	ID_MOTOR_2_OUT_CCW_TIME = ID_MOTOR_2_OUT_CW_TIME + 2,
	ID_MOTOR_2_OUT_STOP_TIME = ID_MOTOR_2_OUT_CCW_TIME + 2,
	
	ID_ACTUATOR_1_OP_TIME = ID_MOTOR_2_OUT_STOP_TIME + 2,
	
	ID_MOTOR_3_OP_TIME = ID_ACTUATOR_1_OP_TIME + 2,
	
	ID_HEATER_1_OP_TIME = ID_MOTOR_3_OP_TIME + 2,
	ID_HEATER_1_TEMP_UP_LIMIT_TIME = ID_HEATER_1_OP_TIME + 2,
	
	ID_PUMP_2_OP_TIME = ID_HEATER_1_TEMP_UP_LIMIT_TIME + 2,
	
	ID_MOTOR_4_OP_TIME = ID_PUMP_2_OP_TIME + 2,
	ID_MOTOR_4_CW_TIME = ID_MOTOR_4_OP_TIME + 2,
	ID_MOTOR_4_CCW_TIME = ID_MOTOR_4_CW_TIME + 2,
	
	ID_MOTOR_5_OP_TIME = ID_MOTOR_4_CCW_TIME + 2,
	ID_MOTOR_5_ON_TIME = ID_MOTOR_5_OP_TIME + 2,
	ID_MOTOR_5_OFF_TIME = ID_MOTOR_5_ON_TIME + 2,
	
	ID_MOTOR_6_OP_TIME = ID_MOTOR_5_OFF_TIME + 2,
	ID_MOTOR_6_CW_TIME = ID_MOTOR_6_OP_TIME + 2,
	ID_MOTOR_6_CCW_TIME = ID_MOTOR_6_CW_TIME + 2,
	
	ID_MOTOR_7_OP_TIME = ID_MOTOR_6_CCW_TIME + 2,
	ID_MOTOR_7_SET_RPM = ID_MOTOR_7_OP_TIME + 2,
	
	ID_RADIATOR_ON_TEMP = ID_MOTOR_7_SET_RPM + 2,
	ID_RADIATOR_OFF_TEMP = ID_RADIATOR_ON_TEMP + 2,
	
	ID_HYSTERESIS_TIME = ID_RADIATOR_OFF_TEMP + 2,
	
	ID_RTC_DATE = ID_HYSTERESIS_TIME + 2,
	ID_RTC_TIME = ID_RTC_DATE + 2,
	
	END_REGISTER,

} modbus_server_id_e;

extern slave_data_t environment_sensor[ENVIRONMENT_SENSOR_MAX];
extern slave_data_t power_meter[POWER_METER_MAX];
extern slave_data_t temperature_controller[TEMPERATURE_CONTROLLER_MAX];

extern uint16_t registers_nmbs_server[REGS_ADDR_MAX + 1];
extern uint16_t registers_nmbs_system_parameter[REGS_SYSTEM_PARAMETER_ADDR_MAX + 1];

extern uint8_t registers_nmbs_server_write_flag;

void environment_sensor_handler(uint32_t id);
void power_meter_handler(uint32_t id);
void environment_sensor_error(uint32_t id);
void power_meter_error(uint32_t id);

void modbus_server_update_handler(void);
void modbus_server_write_handler(uint32_t addr);

void ModbusRTU_Init(void);
void ModbusRTU_Process(void);

#endif /* __USER_MODBUS_H__ */