#include "user_common.h"

eeprom_t eeprom;

const system_parameter_t default_params = 
{
	.ID_EEPROM_ID = DEFAULT_EEPROM_ID,
    .ID_VALVE_1_INTERVAL = DEFAULT_VALVE_1_INTERVAL,
	.ID_VALVE_1_START_TIME_1 = DEFAULT_VALVE_1_START_TIME_1,
	.ID_VALVE_1_START_TIME_2 = DEFAULT_VALVE_1_START_TIME_2,
	.ID_VALVE_1_START_TIME_3 = DEFAULT_VALVE_1_START_TIME_3,
	.ID_VALVE_1_START_TIME_4 = DEFAULT_VALVE_1_START_TIME_4,
	.ID_VALVE_1_START_TIME_5 = DEFAULT_VALVE_1_START_TIME_5,
	.ID_VALVE_1_START_TIME_6 = DEFAULT_VALVE_1_START_TIME_6,
	.ID_VALVE_1_START_TIME_7 = DEFAULT_VALVE_1_START_TIME_7,
	.ID_VALVE_1_START_TIME_8 = DEFAULT_VALVE_1_START_TIME_8,
	.ID_VALVE_1_START_TIME_9 = DEFAULT_VALVE_1_START_TIME_9,
	.ID_VALVE_1_START_TIME_10 = DEFAULT_VALVE_1_START_TIME_10,
	.ID_VALVE_1_ON_TIME = DEFAULT_VALVE_1_ON_TIME,
	
	.ID_PUMP_1_ON_DELAY = DEFAULT_PUMP_1_ON_DELAY,
	
	.ID_UV_LAMP_OFF_DELAY = DEFAULT_UV_LAMP_OFF_DELAY,
	
	.ID_AERATION_3_OFF_DELAY = DEFAULT_AERATION_3_OFF_DELAY,
	
	.ID_PUMP_3_INTERVAL = DEFAULT_PUMP_3_INTERVAL,
	.ID_PUMP_3_START_TIME_1 = DEFAULT_PUMP_3_START_TIME_1,
	.ID_PUMP_3_START_TIME_2 = DEFAULT_PUMP_3_START_TIME_2,
	.ID_PUMP_3_START_TIME_3 = DEFAULT_PUMP_3_START_TIME_3,
	.ID_PUMP_3_START_TIME_4 = DEFAULT_PUMP_3_START_TIME_4,
	.ID_PUMP_3_START_TIME_5 = DEFAULT_PUMP_3_START_TIME_5,
	.ID_PUMP_3_ON_TIME = DEFAULT_PUMP_3_ON_TIME,
	
	.ID_WATER_PUMP_4_TIMEOUT = DEFAULT_WATER_PUMP_4_TIMEOUT,
	
	.ID_SLUDGE_DISCHARGE_INTERVAL = DEFAULT_SLUDGE_DISCHARGE_INTERVAL,
	.ID_SLUDGE_DISCHARGE_START_TIME_1 = DEFAULT_SLUDGE_DISCHARGE_START_TIME_1,
	.ID_SLUDGE_DISCHARGE_START_TIME_2 = DEFAULT_SLUDGE_DISCHARGE_START_TIME_2,
	.ID_SLUDGE_DISCHARGE_START_TIME_3 = DEFAULT_SLUDGE_DISCHARGE_START_TIME_3,
	.ID_SLUDGE_DISCHARGE_START_TIME_4 = DEFAULT_SLUDGE_DISCHARGE_START_TIME_4,
	.ID_SLUDGE_DISCHARGE_START_TIME_5 = DEFAULT_SLUDGE_DISCHARGE_START_TIME_5,
	.ID_SLUDGE_DISCHARGE_START_TIME_6 = DEFAULT_SLUDGE_DISCHARGE_START_TIME_6,
	.ID_SLUDGE_DISCHARGE_START_TIME_7 = DEFAULT_SLUDGE_DISCHARGE_START_TIME_7,
	.ID_SLUDGE_DISCHARGE_START_TIME_8 = DEFAULT_SLUDGE_DISCHARGE_START_TIME_8,
	.ID_SLUDGE_DISCHARGE_START_TIME_9 = DEFAULT_SLUDGE_DISCHARGE_START_TIME_9,
	.ID_SLUDGE_DISCHARGE_START_TIME_10 = DEFAULT_SLUDGE_DISCHARGE_START_TIME_10,

	.ID_WATER_PUMP_1_ON_TIME = DEFAULT_WATER_PUMP_1_ON_TIME,

	.ID_WATER_PUMP_2_ON_TIME = DEFAULT_WATER_PUMP_2_ON_TIME,

	.ID_VALVE_3_ON_TIME = DEFAULT_VALVE_3_ON_TIME,
	.ID_VALVE_3_OFF_DELAY = DEFAULT_VALVE_3_OFF_DELAY,
	.ID_VALVE_4_ON_TIME = DEFAULT_VALVE_4_ON_TIME,
	.ID_VALVE_4_OFF_DELAY = DEFAULT_VALVE_4_OFF_DELAY,
	.ID_VALVE_5_ON_TIME = DEFAULT_VALVE_5_ON_TIME,
	.ID_VALVE_5_OFF_DELAY = DEFAULT_VALVE_5_OFF_DELAY,
	.ID_VALVE_6_ON_TIME = DEFAULT_VALVE_6_ON_TIME,
	.ID_VALVE_6_OFF_DELAY = DEFAULT_VALVE_6_OFF_DELAY,
	
	.ID_MOTOR_8_OFF_DELAY = DEFAULT_MOTOR_8_OFF_DELAY,
	
	.ID_WATER_PUMP_5_INTERVAL = DEFAULT_WATER_PUMP_5_INTERVAL,
	.ID_WATER_PUMP_5_START_TIME_1 = DEFAULT_WATER_PUMP_5_START_TIME_1,
	.ID_WATER_PUMP_5_START_TIME_2 = DEFAULT_WATER_PUMP_5_START_TIME_2,
	.ID_WATER_PUMP_5_START_TIME_3 = DEFAULT_WATER_PUMP_5_START_TIME_3,
	.ID_WATER_PUMP_5_START_TIME_4 = DEFAULT_WATER_PUMP_5_START_TIME_4,
	.ID_WATER_PUMP_5_START_TIME_5 = DEFAULT_WATER_PUMP_5_START_TIME_5,
	.ID_WATER_PUMP_5_START_TIME_6 = DEFAULT_WATER_PUMP_5_START_TIME_6,
	.ID_WATER_PUMP_5_START_TIME_7 = DEFAULT_WATER_PUMP_5_START_TIME_7,
	.ID_WATER_PUMP_5_START_TIME_8 = DEFAULT_WATER_PUMP_5_START_TIME_8,
	.ID_WATER_PUMP_5_START_TIME_9 = DEFAULT_WATER_PUMP_5_START_TIME_9,
	.ID_WATER_PUMP_5_START_TIME_10 = DEFAULT_WATER_PUMP_5_START_TIME_10,
	.ID_WATER_PUMP_5_START_TIME_11 = DEFAULT_WATER_PUMP_5_START_TIME_11,
	.ID_WATER_PUMP_5_START_TIME_12 = DEFAULT_WATER_PUMP_5_START_TIME_12,
	.ID_WATER_PUMP_5_START_TIME_13 = DEFAULT_WATER_PUMP_5_START_TIME_13,
	.ID_WATER_PUMP_5_START_TIME_14 = DEFAULT_WATER_PUMP_5_START_TIME_14,
	.ID_WATER_PUMP_5_START_TIME_15 = DEFAULT_WATER_PUMP_5_START_TIME_15,
	.ID_WATER_PUMP_5_START_TIME_16 = DEFAULT_WATER_PUMP_5_START_TIME_16,
	.ID_WATER_PUMP_5_START_TIME_17 = DEFAULT_WATER_PUMP_5_START_TIME_17,
	.ID_WATER_PUMP_5_START_TIME_18 = DEFAULT_WATER_PUMP_5_START_TIME_18,
	.ID_WATER_PUMP_5_START_TIME_19 = DEFAULT_WATER_PUMP_5_START_TIME_19,
	.ID_WATER_PUMP_5_START_TIME_20 = DEFAULT_WATER_PUMP_5_START_TIME_20,
	.ID_WATER_PUMP_5_START_TIME_21 = DEFAULT_WATER_PUMP_5_START_TIME_21,
	.ID_WATER_PUMP_5_START_TIME_22 = DEFAULT_WATER_PUMP_5_START_TIME_22,
	.ID_WATER_PUMP_5_START_TIME_23 = DEFAULT_WATER_PUMP_5_START_TIME_23,
	.ID_WATER_PUMP_5_START_TIME_24 = DEFAULT_WATER_PUMP_5_START_TIME_24,
	.ID_WATER_PUMP_5_ON_TIME = DEFAULT_WATER_PUMP_5_ON_TIME,

	.ID_VALVE_2_ON_DELAY_1 = DEFAULT_VALVE_2_ON_DELAY_1,
	.ID_VALVE_2_ON_DELAY_2 = DEFAULT_VALVE_2_ON_DELAY_2,
	.ID_VALVE_2_ON_DELAY_3 = DEFAULT_VALVE_2_ON_DELAY_3,
	.ID_VALVE_2_ON_DELAY_4 = DEFAULT_VALVE_2_ON_DELAY_4,
	.ID_VALVE_2_ON_DELAY_5 = DEFAULT_VALVE_2_ON_DELAY_5,
	.ID_VALVE_2_ON_DELAY_6 = DEFAULT_VALVE_2_ON_DELAY_6,
	.ID_VALVE_2_ON_DELAY_7 = DEFAULT_VALVE_2_ON_DELAY_7,
	.ID_VALVE_2_ON_DELAY_8 = DEFAULT_VALVE_2_ON_DELAY_8,
	.ID_VALVE_2_ON_DELAY_9 = DEFAULT_VALVE_2_ON_DELAY_9,
	.ID_VALVE_2_ON_DELAY_10 = DEFAULT_VALVE_2_ON_DELAY_10,
	.ID_VALVE_2_ON_TIME = DEFAULT_VALVE_2_ON_TIME,

	.ID_MOTOR_1_OP_TIME = DEFAULT_MOTOR_1_OP_TIME,
	.ID_MOTOR_1_CW_TIME = DEFAULT_MOTOR_1_CW_TIME,
	.ID_MOTOR_1_CCW_TIME = DEFAULT_MOTOR_1_CCW_TIME,
	.ID_MOTOR_1_STOP_TIME = DEFAULT_MOTOR_1_STOP_TIME,
	
	.ID_FAN_1_OP_TIME = DEFAULT_FAN_1_OP_TIME,
	.ID_FAN_2_OP_TIME = DEFAULT_FAN_2_OP_TIME,
	.ID_PTC_FAN_OP_TIME = DEFAULT_PTC_FAN_OP_TIME,
	
	.ID_MOTOR_2_DRY_OP_TIME = DEFAULT_MOTOR_2_DRY_OP_TIME,
	.ID_MOTOR_2_DRY_CW_TIME = DEFAULT_MOTOR_2_DRY_CW_TIME,
	.ID_MOTOR_2_DRY_CCW_TIME = DEFAULT_MOTOR_2_DRY_CCW_TIME,
	.ID_MOTOR_2_DRY_STOP_TIME = DEFAULT_MOTOR_2_DRY_STOP_TIME,
	.ID_MOTOR_2_CRUSH_OP_TIME = DEFAULT_MOTOR_2_CRUSH_OP_TIME,
	.ID_MOTOR_2_CRUSH_CW_TIME = DEFAULT_MOTOR_2_CRUSH_CW_TIME,
	.ID_MOTOR_2_CRUSH_CCW_TIME = DEFAULT_MOTOR_2_CRUSH_CCW_TIME,
	.ID_MOTOR_2_CRUSH_STOP_TIME = DEFAULT_MOTOR_2_CRUSH_STOP_TIME,
	.ID_MOTOR_2_OUT_OP_TIME = DEFAULT_MOTOR_2_OUT_OP_TIME,
	.ID_MOTOR_2_OUT_CW_TIME = DEFAULT_MOTOR_2_OUT_CW_TIME,
	.ID_MOTOR_2_OUT_CCW_TIME = DEFAULT_MOTOR_2_OUT_CCW_TIME,
	.ID_MOTOR_2_OUT_STOP_TIME = DEFAULT_MOTOR_2_OUT_STOP_TIME,
	
	.ID_ACTUATOR_1_OP_TIME = DEFAULT_ACTUATOR_1_OP_TIME,
	
	.ID_MOTOR_3_OP_TIME = DEFAULT_MOTOR_3_OP_TIME,
	
	.ID_HEATER_1_OP_TIME = DEFAULT_HEATER_1_OP_TIME,
	.ID_HEATER_1_TEMP_UP_LIMIT_TIME = DEFAULT_HEATER_1_TEMP_UP_LIMIT_TIME,
	
	.ID_PUMP_2_OP_TIME = DEFAULT_PUMP_2_OP_TIME,
	
	.ID_MOTOR_4_OP_TIME = DEFAULT_MOTOR_4_OP_TIME,
	.ID_MOTOR_4_CW_TIME = DEFAULT_MOTOR_4_CW_TIME,
	.ID_MOTOR_4_CCW_TIME = DEFAULT_MOTOR_4_CCW_TIME,
	
	.ID_MOTOR_5_OP_TIME = DEFAULT_MOTOR_5_OP_TIME,
	.ID_MOTOR_5_ON_TIME = DEFAULT_MOTOR_5_ON_TIME,
	.ID_MOTOR_5_OFF_TIME = DEFAULT_MOTOR_5_OFF_TIME,
	
	.ID_MOTOR_6_OP_TIME = DEFAULT_MOTOR_6_OP_TIME,
	.ID_MOTOR_6_CW_TIME = DEFAULT_MOTOR_6_CW_TIME,
	.ID_MOTOR_6_CCW_TIME = DEFAULT_MOTOR_6_CCW_TIME,
	
	.ID_MOTOR_7_OP_TIME = DEFAULT_MOTOR_7_OP_TIME,
	.ID_MOTOR_7_SET_RPM = DEFAULT_MOTOR_7_SET_RPM,
	
	.ID_RADIATOR_ON_TEMP = DEFAULT_RADIATOR_ON_TEMP,
	.ID_RADIATOR_OFF_TEMP = DEFAULT_RADIATOR_OFF_TEMP,
	
	.ID_HYSTERESIS_TIME = DEFAULT_HYSTERESIS_TIME,
	
    .ID_RTC_DATE = DEFAULT_RTC_DATE,
    .ID_RTC_TIME = DEFAULT_RTC_TIME,
};

static void eeprom_DefaultSet(void)
{
	uint32_t i = 0, j = 0;
	uint32_t data = 0, index = 0;
	uint32_t Crc = 0;
	
	memset(eeprom.Data, 0, eeprom_Size);
	
	memcpy(&sp, &default_params, sizeof(system_parameter_t));
    memcpy(eeprom.Data, &sp, sizeof(system_parameter_t));
	
	Crc = crc16_ccitt(&eeprom.Data[0], eeprom_Crc);
	memcpy(&eeprom.Data[eeprom_Crc], &Crc, 4);
	
	SYS_UnlockReg();
	FMC_Open();
	FMC_EnableSPUpdate();
	
	FMC_Erase(FMC_SPROM_BASE);
	
	for(i = 0; i < eeprom_Size; i += 4)
	{
		memcpy(&data, &eeprom.Data[i], 4);
		FMC_Write(FMC_SPROM_BASE + i, data);
	}
	
	FMC_DisableSPUpdate();
	FMC_Close();
	SYS_LockReg();
}

void eeprom_Read(void)
{
	uint32_t i = 0, data = 0;
	uint32_t CalcCrc = 0, ReadCrc = 0;
	
	SYS_UnlockReg();
	FMC_Open();
	FMC_EnableSPUpdate();
	
	for(i = 0; i < eeprom_Size; i+= 4)
	{
		data = FMC_Read(FMC_SPROM_BASE + i);
        memcpy(&eeprom.Data[i], &data, 4);
	}
	
	FMC_DisableSPUpdate();
	FMC_Close();
	SYS_LockReg();
	
	if(eeprom.Data[eeprom_ID] != 0x5a)
	{
		eeprom_DefaultSet();
	}
	else
	{
		CalcCrc = crc16_ccitt(&eeprom.Data[0], eeprom_Crc);
		memcpy(&ReadCrc, &eeprom.Data[eeprom_Crc], 4);
		
		if(CalcCrc != ReadCrc)
		{
			eeprom_DefaultSet();
		}
		else
		{
			memcpy(&sp, &eeprom.Data, sizeof(system_parameter_t));
		}
	}
	
	/*if(eeprom_ValidData() == FALSE)
	{
		eeprom_Write();
	}*/
}

void eeprom_Write(void)
{
	uint32_t i = 0, j = 0;
	uint32_t data = 0, index = 0;
	uint8_t ModifyData[eeprom_Size] = {0,};
	uint32_t writeCrc = 0, eepromCrc = 0;
	
	memcpy(ModifyData, &sp, sizeof(system_parameter_t));
	
	writeCrc = crc16_ccitt(&ModifyData[0], eeprom_Crc);
	memcpy(&ModifyData[eeprom_Crc], &writeCrc, 4);
	
	memcpy(&eepromCrc, &eeprom.Data[eeprom_Crc], 4);
	
	if(writeCrc != eepromCrc)
	{
		memcpy(eeprom.Data, ModifyData, eeprom_Size);
		
		SYS_UnlockReg();
		FMC_Open();
		FMC_EnableSPUpdate();
		
		FMC_Erase(FMC_SPROM_BASE);
		
		for(i = 0; i < eeprom_Size; i += 4)
		{
			memcpy(&data, &eeprom.Data[i], 4);
			FMC_Write(FMC_SPROM_BASE + i, data);
		}
		
		FMC_DisableSPUpdate();
		FMC_Close();
		SYS_LockReg();
	}
}
